export enum PostStatus {
  DRAFT = 'draft',
  PUBLISHED = 'published',
  ARCHIVED = 'archived',
}

export enum Category {
  technology = 'technology',
  web_development = 'web_development',
  programming = 'programming',
  ai_machine_learning = 'ai_machine_learning',
  cybersecurity = 'cybersecurity',
  data_science = 'data_science',
  mobile_development = 'mobile_development',
  open_source = 'open_source',
  gadgets_reviews = 'gadgets_reviews',
  startups = 'startups',
  business = 'business',
  marketing = 'marketing',
  entrepreneurship = 'entrepreneurship',
  personal_finance = 'personal_finance',
  investing = 'investing',
  cryptocurrency = 'cryptocurrency',
  real_estate = 'real_estate',
  career_productivity = 'career_productivity',
  remote_work = 'remote_work',
  ecommerce = 'ecommerce',
  health_wellness = 'health_wellness',
  fitness = 'fitness',
  mental_health = 'mental_health',
  food_recipes = 'food_recipes',
  travel = 'travel',
  fashion_beauty = 'fashion_beauty',
  home_diy = 'home_diy',
  parenting = 'parenting',
  relationships = 'relationships',
  self_improvement = 'self_improvement',
  minimalism = 'minimalism',
  sustainability = 'sustainability',
  design = 'design',
  photography = 'photography',
  writing_books = 'writing_books',
  art = 'art',
  music = 'music',
  film_tv = 'film_tv',
  gaming = 'gaming',
  pop_culture = 'pop_culture',
  automotive = 'automotive',
  crafts_hobbies = 'crafts_hobbies',
  education = 'education',
  science = 'science',
  history = 'history',
  politics = 'politics',
  philosophy = 'philosophy',
  nature = 'nature',
  religion_spirituality = 'religion_spirituality',
  opinion_editorial = 'opinion_editorial',
}